encoding: utf-8
port: 5000

title: COCO-2084
author: COCO-2084
author-intro: C/C++ Developer
permalink: /:year/:month/:day/:title/

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# paginate
gems: [jekyll-paginate]
paginate: 6